title: Yilak A Kebede
description: Stuff that I come across and find interesting.
author: Yilak Kebede
email: yilak.akloweg@gmail.com
phone: (647) 219-4528
github: https://github.com/Yilakkebede
about: I am a Software Engineer at <a href="https://www.build.com" target="_blank">Build.com</a> and a freelance developer. I love working on backend and frontend technologies.
disqus_shortname: Data Analyst & Researcher
# google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      # link: "https://www.facebook.com/tjamadar"
    - icon: fa-twitter
      link: "https://twitter.com/yilak.kebede"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/yilak-kebede/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/Yilakkebede"

share:
  twitter_username: yilak.kebede
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://Yilakkebede.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
